### ISSUE TITLE
Nuxt build error

### ISSUE THREAD

**Issue by djengineer** [ansonla3/consensysProject#2]
I am getting this error now. Cant run nuxt.

How do you fix this?
```

 ERROR 

  Error: No build files found, please run `nuxt build` before launching `nuxt st  art`

```

**Comment by ansonla3** [comment]
which command you ran to get this error ?

**Comment by ansonla3** [comment]
did you run npm install ?

**Comment by djengineer** [comment]
Hi! I have resolved this.
> npm install
> npm rebuild

Maybe you can add npm rebuild to your instructions? :)
